### ISSUE TITLE
Incorrect sha256 hash

### ISSUE THREAD

**Issue by nuimk** [Plailect/autofirm#6]
The downloaded firmware files from `11.2.0_to_10.4.0_n3ds.torrent` sha256 hash doesn't match the one list in README.MD

`firm104_NEW.bin` hash is correct. but for `firm112_NEW.bin`, I get `30e97727d78f1c3129e370622ce07894489765ffa272c67fc10ad8f4d1e41735` which is not equal to `04623caa015b46a557894e4693992252b7a45414f2cbcbd4b23a89bbe417c0ff`

I pretty sure that my downloaded file is completed. Can you please help check the sha256 hash?

**Comment by Plailect** [comment]
You are correct. I'll fix this.
