### ISSUE TITLE
Add linux support

### ISSUE THREAD

**Issue by mariogamer2** [Plailect/autofirm#7]
So,as I see,xor is open source,we just need to compile it (I may do it) (and probably most python lib)

I don't know for 3DSFirm,though?

**Comment by Plailect** [comment]
Feel free to pull request.

**Comment by mariogamer2** [comment]
Ok.

Just like this,does .pyc are os only file or it is somewhat universal?

**Comment by Plailect** [comment]
Use bash.

**Comment by mariogamer2** [comment]
You should use this firmswap,since it detect nand type and version. No need to manually specify things.
